@startuml Producer Response Flow

title Producer Sends Response

participant ProducerComponent as PComp
participant PComp_RespThread as PRespT <<Thread>>
participant PComp_Comm as PComm <<Communicator>>
participant ProtocolLayer as Proto
participant NICLayer as NIC
participant Network

== Producer Sends RESPONSE ==

PRespT -> PRespT : Loop wakes based on GCD period.
PRespT -> PComp : "produce_data(DataTypeId X)"
PRespT -> PComm : "new_message(RESPONSE, DataTypeId X, 0, data_value, value_size)"
PComm -> PComm : Create "response_msg"
PRespT -> PComm : "send(response_msg, BROADCAST_MAC:BROADCAST_PORT)"
PComm -> Proto : "send(PComp_Addr, BROADCAST_MAC:BROADCAST_PORT, response_payload, size)"
Proto -> NIC : "send(eth_frame_response)"
NIC -> Network : Transmit Ethernet Frame

@enduml 