@startuml 01-system_sequence_diagram

' Process flow
participant "Vehicle <<Process>>" as Vehicle
participant "Message" as Message
participant "Communicator <<Concurrent_Observer>>" as Communicator
participant "Protocol <<Subject>>" as Protocol
participant "NIC" as NIC
participant "SocketEngine <<Engine>>" as SocketEngine
participant "NIC <<Physical>>" as NIC_Physical

autonumber
Vehicle -> Message: Create
Message -> Vehicle: Message
Vehicle -> Communicator: send(Message)
Communicator -> Protocol: send(address, BROADCAST, data, size)
activate Protocol
Protocol -> NIC: alloc(address, PROTO, size)
NIC --> Protocol: return buffer
note right of Protocol: Copy data to buffer
Protocol -> NIC: send(buffer)
NIC -> SocketEngine: sendto(...)
SocketEngine --> NIC_Physical: send(buffer)
deactivate Protocol

==== Network Layer Boundary ====

' NIC receives data from the network
NIC_Physical <-: F 
NIC_Physical -> SocketEngine: Interruption
SocketEngine -> NIC: notify(PROTO, buffer)
NIC -> Protocol: notify(PROTO, buffer)
Protocol -> Protocol: update(&_observed, PROTO, buffer)
Protocol -> Communicator: notify(condition, data)
Communicator -> Communicator: update(condition, data)
note right of Communicator: Calls update and releases the thread waiting for data
Vehicle -> Communicator: receive(Message)
note right of Vehicle: Updated that data is available

@enduml 