@startuml 02-process_thread_diagram

' Style definitions
skinparam componentStyle rectangle
skinparam backgroundColor white
skinparam linetype ortho

' Process Components
package "Process" {
  package "Component" {
    component [Comm] as comm1
  }
  component [Prot.] as prot1
  component [NIC] as nic1
  component [SocketEngine] as SocketEngine1
  
  comm1 --> prot1
  prot1 --> nic1
  nic1 -|> SocketEngine1
}

' Second Process with Threads
package "Process'" {
  package "Component'" {
    component [Comm] as comm2
  }
    component [Prot.] as prot2
    component [NIC] as nic2
    component [SocketEngine] as SocketEngine2
    
  nic2 -|> SocketEngine2
  prot2 <-- nic2 
  comm2 <-- prot2 
}

' Kernel architecture section
package "Kernel" {
  component [Socket] as socket
  
  SocketEngine1 --> socket
  nic2 <-- socket
}

@enduml 